import apisauce from 'apisauce'

const create = (baseURL = 'https://sib.gob.ar/api/2.0.0') => {

   const api = apisauce.create({
      baseURL,
      Headers,
      TIMEOUT: 10000
   })

   // const getId = (id) => api.get(`/punto-interes/${id}`)
   // const getList = () => api.get(`/ficha-area-protegida/parque-nacional-los-glaciares/punto-interes`)
   // const search = (name) => api.get('/ficha-area-protegida/parque-nacional-los-glaciares/search/punto-interes', {q: name})

   jsonPuntoInteres = {
      "type": "Feature",
      "properties":{ 
         "Name": "Laguna Negra", 
         "description": "descripción: <br>TIPO: TURBAL<br>NOMBRE: LAGUNA NEGRA<br>ROTULO: Laguna Negra<br>LATITUD: 54° 50' 24.29\" S<br>LONGITUD: 68° 35' 22.61\" W<br>ALTITUD: 23<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Laguna Negra", 
         "timestamp": null, 
         "begin": null, 
         "end": null, 
         "altitudeMode": null, 
         "tessellate": -1, 
         "extrude": 0, 
         "visibility": -1, 
         "drawOrder": null, 
         "icon": null, 
         "descripci__n": "", 
         "TIPO": "TURBAL", 
         "NOMBRE": "LAGUNA NEGRA", 
         "ROTULO": "Laguna Negra", 
         "LATITUD": "54° 50' 24.29\" S", 
         "LONGITUD": "68° 35' 22.61\" W", 
         "ALTITUD": "23", 
         "AREA_PROTE": "Parque Nacional Tierra del Fuego" 
      },
      "geometry": { 
         "type": "Point", 
         "coordinates": [ -68.589615, -54.840083, 0.0 ] 
      } 
   }

   jsonPuntoInteresLists = {
      "type": "FeatureCollection",
      "name": "puntos_interes-pn-tdf",
      "features": [
         { "type": "Feature", "properties": { "Name": "Secc. Fenochio", "description": "descripción: <br>TIPO: SECCIONAL<br>NOMBRE: FENOCHIO<br>ROTULO: Secc. Fenochio<br>LATITUD: 54° 50' 5.073\" S<br>LONGITUD: 68° 33' 37.00\" W<br>ALTITUD: 30<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Secc. Fenochio", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "SECCIONAL", "NOMBRE": "FENOCHIO", "ROTULO": "Secc. Fenochio", "LATITUD": "54° 50' 5.073\" S", "LONGITUD": "68° 33' 37.00\" W", "ALTITUD": "30", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.560278, -54.834743, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Secc. Lapataia", "description": "descripción: <br>TIPO: SECCIONAL<br>NOMBRE: LAPATAIA<br>ROTULO: Secc. Lapataia<br>LATITUD: 54° 50' 37.88\" S<br>LONGITUD: 68° 33' 34.40\" W<br>ALTITUD: 10<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Secc. Lapataia", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "SECCIONAL", "NOMBRE": "LAPATAIA", "ROTULO": "Secc. Lapataia", "LATITUD": "54° 50' 37.88\" S", "LONGITUD": "68° 33' 34.40\" W", "ALTITUD": "10", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.559558, -54.843858, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Secc. La Portada", "description": "descripción: <br>TIPO: SECCIONAL<br>NOMBRE: LA PORTADA<br>ROTULO: Secc. La Portada<br>LATITUD: 54° 50' 5.079\" S<br>LONGITUD: 68° 26' 52.37\" W<br>ALTITUD: 138<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Secc. La Portada", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "SECCIONAL", "NOMBRE": "LA PORTADA", "ROTULO": "Secc. La Portada", "LATITUD": "54° 50' 5.079\" S", "LONGITUD": "68° 26' 52.37\" W", "ALTITUD": "138", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.447883, -54.834744, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Intendencia PNTF", "description": "descripción: <br>TIPO: INTENDENCIA<br>NOMBRE: INTENDENCIA PNTDF<br>ROTULO: Intendencia PNTF<br>LATITUD: 54° 48' 33.68\" S<br>LONGITUD: 68° 19' 1.365\" W<br>ALTITUD: 19<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Intendencia PNTF", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "INTENDENCIA", "NOMBRE": "INTENDENCIA PNTDF", "ROTULO": "Intendencia PNTF", "LATITUD": "54° 48' 33.68\" S", "LONGITUD": "68° 19' 1.365\" W", "ALTITUD": "19", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.317046, -54.809357, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Centro de Visitantes Alakush", "description": "descripción: <br>TIPO: CENTRO DE VISITANTES<br>NOMBRE: ALAKUSH<br>ROTULO: Centro de Visitantes Alakush<br>LATITUD: 54° 50' 14.82\" S<br>LONGITUD: 68° 33' 42.76\" W<br>ALTITUD: 14<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Centro de Visitantes Alakush", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "CENTRO DE VISITANTES", "NOMBRE": "ALAKUSH", "ROTULO": "Centro de Visitantes Alakush", "LATITUD": "54° 50' 14.82\" S", "LONGITUD": "68° 33' 42.76\" W", "ALTITUD": "14", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561879, -54.83745, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Laguna Negra", "description": "descripción: <br>TIPO: TURBAL<br>NOMBRE: LAGUNA NEGRA<br>ROTULO: Laguna Negra<br>LATITUD: 54° 50' 24.29\" S<br>LONGITUD: 68° 35' 22.61\" W<br>ALTITUD: 23<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Laguna Negra", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TURBAL", "NOMBRE": "LAGUNA NEGRA", "ROTULO": "Laguna Negra", "LATITUD": "54° 50' 24.29\" S", "LONGITUD": "68° 35' 22.61\" W", "ALTITUD": "23", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.589615, -54.840083, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Cascada Rio Pipo", "description": "descripción: <br>TIPO: PUNTO PANORAMICO<br>NOMBRE: CASCADA RÍO PIPO<br>ROTULO: Cascada Río Pipo<br>LATITUD: 54° 48' 52.76\" S<br>LONGITUD: 68° 28' 46.80\" W<br>ALTITUD: 126<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Cascada Rio Pipo", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PUNTO PANORAMICO", "NOMBRE": "CASCADA RÍO PIPO", "ROTULO": "Cascada Río Pipo", "LATITUD": "54° 48' 52.76\" S", "LONGITUD": "68° 28' 46.80\" W", "ALTITUD": "126", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.479667, -54.814656, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Ensenada Zaratiegui", "description": "descripción: <br>TIPO: PUNTO PANORAMICO<br>NOMBRE: ENSENADA ZARATIEGUI<br>ROTULO: Ensenada Zaratiegui<br>LATITUD: 54° 50' 48.20\" S<br>LONGITUD: 68° 28' 52.21\" W<br>ALTITUD: 8<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Ensenada Zaratiegui", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PUNTO PANORAMICO", "NOMBRE": "ENSENADA ZARATIEGUI", "ROTULO": "Ensenada Zaratiegui", "LATITUD": "54° 50' 48.20\" S", "LONGITUD": "68° 28' 52.21\" W", "ALTITUD": "8", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.481171, -54.846725, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Lago Roca - Acigami", "description": "descripción: <br>TIPO: PUNTO PANORAMICO<br>NOMBRE: LAGO ROCA - ACIGAMI<br>ROTULO: Lago Roca - Acigami<br>LATITUD: 54° 49' 29.41\" S<br>LONGITUD: 68° 34' 27.49\" W<br>ALTITUD: 4<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Lago Roca - Acigami", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PUNTO PANORAMICO", "NOMBRE": "LAGO ROCA - ACIGAMI", "ROTULO": "Lago Roca - Acigami", "LATITUD": "54° 49' 29.41\" S", "LONGITUD": "68° 34' 27.49\" W", "ALTITUD": "4", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.574304, -54.824839, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Bahia Lapataia", "description": "descripción: <br>TIPO: PUNTO PANORAMICO<br>NOMBRE: LAPATAIA<br>ROTULO: Lapataia<br>LATITUD: 54° 51' 16.90\" S<br>LONGITUD: 68° 34' 19.87\" W<br>ALTITUD: 0<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Bahia Lapataia", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PUNTO PANORAMICO", "NOMBRE": "LAPATAIA", "ROTULO": "Lapataia", "LATITUD": "54° 51' 16.90\" S", "LONGITUD": "68° 34' 19.87\" W", "ALTITUD": "0", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.572188, -54.854695, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Cartel Fin Ruta 3", "description": "descripción: <br>TIPO: CARTEL<br>NOMBRE: FIN RUTA PANAMERICANA<br>ROTULO: Fin ruta Panamericana (Nº3)<br>LATITUD: 54° 51' 19.03\" S<br>LONGITUD: 68° 34' 34.74\" W<br>ALTITUD: 6<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Cartel Fin Ruta 3", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "CARTEL", "NOMBRE": "FIN RUTA PANAMERICANA", "ROTULO": "Fin ruta Panamericana (Nº3)", "LATITUD": "54° 51' 19.03\" S", "LONGITUD": "68° 34' 34.74\" W", "ALTITUD": "6", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.576317, -54.855288, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Laguna del Caminante", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: LAGUNA DEL CAMINANTE<br>ROTULO: Laguna del Caminante<br>LATITUD: 54° 45' 28.39\" S<br>LONGITUD: 68° 26' 35.08\" W<br>ALTITUD: 588<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Laguna del Caminante", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "LAGUNA DEL CAMINANTE", "ROTULO": "Laguna del Caminante", "LATITUD": "54° 45' 28.39\" S", "LONGITUD": "68° 26' 35.08\" W", "ALTITUD": "588", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.44308, -54.757888, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Valle de Andorra", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: VALLE DE ANDORRA<br>ROTULO: Valle de Andorra<br>LATITUD: 54° 45' 16.74\" S<br>LONGITUD: 68° 22' 5.291\" W<br>ALTITUD: 280<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Valle de Andorra", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "VALLE DE ANDORRA", "ROTULO": "Valle de Andorra", "LATITUD": "54° 45' 16.74\" S", "LONGITUD": "68° 22' 5.291\" W", "ALTITUD": "280", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.368137, -54.754651, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "P. Ishton", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: PENINSULA ISHTON<br>ROTULO: Península Ishton<br>LATITUD: 54° 51' 32.77\" S<br>LONGITUD: 68° 27' 34.66\" W<br>ALTITUD: 6<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: P. Ishton", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "PENINSULA ISHTON", "ROTULO": "Península Ishton", "LATITUD": "54° 51' 32.77\" S", "LONGITUD": "68° 27' 34.66\" W", "ALTITUD": "6", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.459628, -54.859103, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Isla Estorbo", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: ISLA ESTORBO<br>ROTULO: Isla Estorbo<br>LATITUD: 54° 51' 48.48\" S<br>LONGITUD: 68° 27' 20.84\" W<br>ALTITUD: 17<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Isla Estorbo", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "ISLA ESTORBO", "ROTULO": "Isla Estorbo", "LATITUD": "54° 51' 48.48\" S", "LONGITUD": "68° 27' 20.84\" W", "ALTITUD": "17", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.455791, -54.863467, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Punta Entrada", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: PUNTA ENTRADA<br>ROTULO: Punta Entrada<br>LATITUD: 54° 52' 2.166\" S<br>LONGITUD: 68° 30' 5.203\" W<br>ALTITUD: 8<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Punta Entrada", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "PUNTA ENTRADA", "ROTULO": "Punta Entrada", "LATITUD": "54° 52' 2.166\" S", "LONGITUD": "68° 30' 5.203\" W", "ALTITUD": "8", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.501445, -54.867268, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Isla Salmón", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: ISLA SALMON<br>ROTULO: Isla Salmón<br>LATITUD: 54° 50' 6.075\" S<br>LONGITUD: 68° 33' 58.37\" W<br>ALTITUD: 5<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Isla Salmón", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "ISLA SALMON", "ROTULO": "Isla Salmón", "LATITUD": "54° 50' 6.075\" S", "LONGITUD": "68° 33' 58.37\" W", "ALTITUD": "5", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.566214, -54.835021, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Bahía Cucharita", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: BAHIA CUCHARITA<br>ROTULO: Bahía Cucharita<br>LATITUD: 54° 51' 23.11\" S<br>LONGITUD: 68° 27' 25.78\" W<br>ALTITUD: 7<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Bahía Cucharita", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "BAHIA CUCHARITA", "ROTULO": "Bahía Cucharita", "LATITUD": "54° 51' 23.11\" S", "LONGITUD": "68° 27' 25.78\" W", "ALTITUD": "7", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.457161, -54.856421, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Cerro Bellavista", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: CERRO BELLAVISTA<br>ROTULO: Cerro Bellavista<br>LATITUD: 54° 50' 57.25\" S<br>LONGITUD: 68° 31' 12.05\" W<br>ALTITUD: 267<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Cerro Bellavista", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "CERRO BELLAVISTA", "ROTULO": "Cerro Bellavista", "LATITUD": "54° 50' 57.25\" S", "LONGITUD": "68° 31' 12.05\" W", "ALTITUD": "267", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.520016, -54.849238, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Confiteria", "description": "descripción: <br>TIPO: RESTAURANTE<br>NOMBRE: ALAKUSH<br>ROTULO: Confiteria<br>LATITUD: 54° 50' 14.42\" S<br>LONGITUD: 68° 33' 43.51\" W<br>ALTITUD: 12<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Confiteria", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "RESTAURANTE", "NOMBRE": "ALAKUSH", "ROTULO": "Confiteria", "LATITUD": "54° 50' 14.42\" S", "LONGITUD": "68° 33' 43.51\" W", "ALTITUD": "12", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.562087, -54.837341, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 6", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 49' 49.26\" S<br>LONGITUD: 68° 33' 47.31\" W<br>ALTITUD: 9<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 6", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 49' 49.26\" S", "LONGITUD": "68° 33' 47.31\" W", "ALTITUD": "9", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.563143, -54.830351, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 5", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 50' 46.12\" S<br>LONGITUD: 68° 34' 45.75\" W<br>ALTITUD: 5<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 5", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 50' 46.12\" S", "LONGITUD": "68° 34' 45.75\" W", "ALTITUD": "5", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.579377, -54.846146, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 4", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 50' 47.04\" S<br>LONGITUD: 68° 28' 53.06\" W<br>ALTITUD: 13<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 4", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 50' 47.04\" S", "LONGITUD": "68° 28' 53.06\" W", "ALTITUD": "13", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.481406, -54.846402, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 3", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 50' 11.45\" S<br>LONGITUD: 68° 28' 17.45\" W<br>ALTITUD: 125<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 3", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 50' 11.45\" S", "LONGITUD": "68° 28' 17.45\" W", "ALTITUD": "125", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.471516, -54.836516, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 2", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 50' 16.67\" S<br>LONGITUD: 68° 33' 42.44\" W<br>ALTITUD: 12<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 2", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 50' 16.67\" S", "LONGITUD": "68° 33' 42.44\" W", "ALTITUD": "12", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561791, -54.837964, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 1", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 51' 18.08\" S<br>LONGITUD: 68° 34' 41.94\" W<br>ALTITUD: 10<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 1", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 51' 18.08\" S", "LONGITUD": "68° 34' 41.94\" W", "ALTITUD": "10", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.578317, -54.855024, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Souvenirs 1", "description": "descripción: <br>TIPO: COMERCIO<br>NOMBRE: SOUVENIRS ALAKUSH<br>ROTULO: Souvenirs<br>LATITUD: 54° 50' 15.10\" S<br>LONGITUD: 68° 33' 41.91\" W<br>ALTITUD: 15<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Souvenirs 1", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "COMERCIO", "NOMBRE": "SOUVENIRS ALAKUSH", "ROTULO": "Souvenirs", "LATITUD": "54° 50' 15.10\" S", "LONGITUD": "68° 33' 41.91\" W", "ALTITUD": "15", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561642, -54.83753, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "FAF", "description": "descripción: <br>TIPO: ESTACION FERROCARRIL<br>NOMBRE: ESTACIÓN FAF<br>ROTULO: Estación FAF<br>LATITUD: 54° 50' 9.483\" S<br>LONGITUD: 68° 28' 16.44\" W<br>ALTITUD: 115<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: FAF", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACION FERROCARRIL", "NOMBRE": "ESTACIÓN FAF", "ROTULO": "Estación FAF", "LATITUD": "54° 50' 9.483\" S", "LONGITUD": "68° 28' 16.44\" W", "ALTITUD": "115", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.471236, -54.835968, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Muelle Puerto Arias", "description": "descripción: <br>TIPO: MUELLE<br>NOMBRE: MUELLE PUERTO ARIAS<br>ROTULO: Muelle Puerto Arias<br>LATITUD: 54° 51' 18.71\" S<br>LONGITUD: 68° 34' 23.82\" W<br>ALTITUD: 2<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Muelle Puerto Arias", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MUELLE", "NOMBRE": "MUELLE PUERTO ARIAS", "ROTULO": "Muelle Puerto Arias", "LATITUD": "54° 51' 18.71\" S", "LONGITUD": "68° 34' 23.82\" W", "ALTITUD": "2", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.573286, -54.8552, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Oficina APN", "description": "descripción: <br>TIPO: OFICINA<br>NOMBRE: OFICINA ALAKUSH<br>ROTULO: Oficina APN<br>LATITUD: 54° 50' 14.85\" S<br>LONGITUD: 68° 33' 42.52\" W<br>ALTITUD: 14<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Oficina APN", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "OFICINA", "NOMBRE": "OFICINA ALAKUSH", "ROTULO": "Oficina APN", "LATITUD": "54° 50' 14.85\" S", "LONGITUD": "68° 33' 42.52\" W", "ALTITUD": "14", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561813, -54.837459, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Oficina de informes la Portada", "description": "descripción: <br>TIPO: OFICINA DE INFORMES<br>NOMBRE: OFICINA DE INFORMES LA PORTADA<br>ROTULO: Oficina de informes La Portada<br>LATITUD: 54° 50' 5.245\" S<br>LONGITUD: 68° 26' 48.23\" W<br>ALTITUD: 132<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Oficina de informes la Portada", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "OFICINA DE INFORMES", "NOMBRE": "OFICINA DE INFORMES LA PORTADA", "ROTULO": "Oficina de informes La Portada", "LATITUD": "54° 50' 5.245\" S", "LONGITUD": "68° 26' 48.23\" W", "ALTITUD": "132", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.446733, -54.83479, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 1", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 51' 18.69\" S<br>LONGITUD: 68° 34' 40.96\" W<br>ALTITUD: 9<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 1", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 51' 18.69\" S", "LONGITUD": "68° 34' 40.96\" W", "ALTITUD": "9", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.578046, -54.855193, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Lapataia", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR BAHIA LAPATAIA<br>ROTULO: Mirador Lapataia<br>LATITUD: 54° 51' 10.81\" S<br>LONGITUD: 68° 34' 40.24\" W<br>ALTITUD: 22<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Lapataia", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR BAHIA LAPATAIA", "ROTULO": "Mirador Lapataia", "LATITUD": "54° 51' 10.81\" S", "LONGITUD": "68° 34' 40.24\" W", "ALTITUD": "22", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.577845, -54.853005, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 2", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 50' 18.35\" S<br>LONGITUD: 68° 33' 41.92\" W<br>ALTITUD: 10<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 2", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 50' 18.35\" S", "LONGITUD": "68° 33' 41.92\" W", "ALTITUD": "10", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561645, -54.838432, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 3", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 50' 5.468\" S<br>LONGITUD: 68° 26' 49.60\" W<br>ALTITUD: 133<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 3", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 50' 5.468\" S", "LONGITUD": "68° 26' 49.60\" W", "ALTITUD": "133", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.447112, -54.834852, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 4", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 49' 49.80\" S<br>LONGITUD: 68° 33' 47.22\" W<br>ALTITUD: 10<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 4", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 49' 49.80\" S", "LONGITUD": "68° 33' 47.22\" W", "ALTITUD": "10", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.563118, -54.830503, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 8", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 50' 40.05\" S<br>LONGITUD: 68° 34' 24.15\" W<br>ALTITUD: 21<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 8", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 50' 40.05\" S", "LONGITUD": "68° 34' 24.15\" W", "ALTITUD": "21", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.573376, -54.844459, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 6", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 50' 48.71\" S<br>LONGITUD: 68° 34' 52.09\" W<br>ALTITUD: 10<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 6", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 50' 48.71\" S", "LONGITUD": "68° 34' 52.09\" W", "ALTITUD": "10", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.581137, -54.846866, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 7", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 51' 19.72\" S<br>LONGITUD: 68° 35' 25.35\" W<br>ALTITUD: 21<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 7", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 51' 19.72\" S", "LONGITUD": "68° 35' 25.35\" W", "ALTITUD": "21", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.590377, -54.85548, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Portada de accceso", "description": "descripción: <br>TIPO: PORTADA<br>NOMBRE: PORTADA<br>ROTULO: Portada<br>LATITUD: 54° 50' 5.741\" S<br>LONGITUD: 68° 26' 41.76\" W<br>ALTITUD: 126<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Portada de accceso", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PORTADA", "NOMBRE": "PORTADA", "ROTULO": "Portada", "LATITUD": "54° 50' 5.741\" S", "LONGITUD": "68° 26' 41.76\" W", "ALTITUD": "126", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.444934, -54.834928, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Casilla de cobro", "description": "descripción: <br>TIPO: CASILLA O PUESTO DE COBRO<br>NOMBRE: CASILLA DE COBRO DE ACCESO<br>ROTULO: Casilla de cobro de acceso<br>LATITUD: 54° 50' 5.878\" S<br>LONGITUD: 68° 26' 48.21\" W<br>ALTITUD: 130<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Casilla de cobro", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "CASILLA O PUESTO DE COBRO", "NOMBRE": "CASILLA DE COBRO DE ACCESO", "ROTULO": "Casilla de cobro de acceso", "LATITUD": "54° 50' 5.878\" S", "LONGITUD": "68° 26' 48.21\" W", "ALTITUD": "130", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.446727, -54.834966, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Isla Redonda", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR ISLA REDONDA<br>ROTULO: Mirador Isla Redonda<br>LATITUD: 54° 50' 31.06\" S<br>LONGITUD: 68° 29' 48.44\" W<br>ALTITUD: 104<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Isla Redonda", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR ISLA REDONDA", "ROTULO": "Mirador Isla Redonda", "LATITUD": "54° 50' 31.06\" S", "LONGITUD": "68° 29' 48.44\" W", "ALTITUD": "104", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.49679, -54.841963, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Laguna Verde", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR LAGUNA VERDE<br>ROTULO: Mirador Laguna Verde<br>LATITUD: 54° 50' 38.56\" S<br>LONGITUD: 68° 34' 27.57\" W<br>ALTITUD: 16<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Laguna Verde", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR LAGUNA VERDE", "ROTULO": "Mirador Laguna Verde", "LATITUD": "54° 50' 38.56\" S", "LONGITUD": "68° 34' 27.57\" W", "ALTITUD": "16", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.574326, -54.844046, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Río Pipo", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR RÍO PIPO<br>ROTULO: Mirador Río Pipo<br>LATITUD: 54° 48' 53.88\" S<br>LONGITUD: 68° 28' 45.89\" W<br>ALTITUD: 123<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Río Pipo", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR RÍO PIPO", "ROTULO": "Mirador Río Pipo", "LATITUD": "54° 48' 53.88\" S", "LONGITUD": "68° 28' 45.89\" W", "ALTITUD": "123", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.479417, -54.814967, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Lago Roca", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR LAGO ROCA<br>ROTULO: Mirador Lago Roca<br>LATITUD: 54° 49' 50.42\" S<br>LONGITUD: 68° 33' 49.37\" W<br>ALTITUD: 8<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Lago Roca", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR LAGO ROCA", "ROTULO": "Mirador Lago Roca", "LATITUD": "54° 49' 50.42\" S", "LONGITUD": "68° 33' 49.37\" W", "ALTITUD": "8", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.563714, -54.830674, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Mirador Alakush", "description": "descripción: <br>TIPO: MIRADOR<br>NOMBRE: MIRADOR ALAKUSH<br>ROTULO: Mirador Alakush<br>LATITUD: 54° 50' 15.04\" S<br>LONGITUD: 68° 33' 42.36\" W<br>ALTITUD: 14<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Mirador Alakush", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "MIRADOR", "NOMBRE": "MIRADOR ALAKUSH", "ROTULO": "Mirador Alakush", "LATITUD": "54° 50' 15.04\" S", "LONGITUD": "68° 33' 42.36\" W", "ALTITUD": "14", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561768, -54.837512, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Centro de interpretacion", "description": "descripción: <br>TIPO: CENTRO DE INTERPRETACION<br>NOMBRE: CENTRO DE INTERPRETACION<br>ROTULO: Centro de interpretacion<br>LATITUD: 54° 50' 15.19\" S<br>LONGITUD: 68° 33' 42.02\" W<br>ALTITUD: 15<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Centro de interpretacion", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "CENTRO DE INTERPRETACION", "NOMBRE": "CENTRO DE INTERPRETACION", "ROTULO": "Centro de interpretacion", "LATITUD": "54° 50' 15.19\" S", "LONGITUD": "68° 33' 42.02\" W", "ALTITUD": "15", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561674, -54.837555, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Area Acampe Cauquenes", "description": "descripción: <br>TIPO: AREA DE ACAMPE <br>NOMBRE: AREA ACAMPE CAUQUENES<br>ROTULO: Area Acampe Cauquenes<br>LATITUD: 54° 50' 46.79\" S<br>LONGITUD: 68° 34' 41.71\" W<br>ALTITUD: 11<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Area Acampe Cauquenes", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "AREA DE ACAMPE ", "NOMBRE": "AREA ACAMPE CAUQUENES", "ROTULO": "Area Acampe Cauquenes", "LATITUD": "54° 50' 46.79\" S", "LONGITUD": "68° 34' 41.71\" W", "ALTITUD": "11", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.578253, -54.846333, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Area Acampe Laguna Verde", "description": "descripción: <br>TIPO: AREA DE ACAMPE <br>NOMBRE: AREA ACAMPE LAGUNA VERDE<br>ROTULO: Area Acampe Laguna Verde<br>LATITUD: 54° 50' 42.13\" S<br>LONGITUD: 68° 34' 44.00\" W<br>ALTITUD: 6<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Area Acampe Laguna Verde", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "AREA DE ACAMPE ", "NOMBRE": "AREA ACAMPE LAGUNA VERDE", "ROTULO": "Area Acampe Laguna Verde", "LATITUD": "54° 50' 42.13\" S", "LONGITUD": "68° 34' 44.00\" W", "ALTITUD": "6", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.57889, -54.845039, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Area de acampe Ensenada", "description": "descripción: <br>TIPO: AREA DE ACAMPE <br>NOMBRE: AREA ACAMPE ENSENADA<br>ROTULO: Area de acampe Ensenada<br>LATITUD: 54° 50' 37.94\" S<br>LONGITUD: 68° 28' 59.77\" W<br>ALTITUD: 41<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Area de acampe Ensenada", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "AREA DE ACAMPE ", "NOMBRE": "AREA ACAMPE ENSENADA", "ROTULO": "Area de acampe Ensenada", "LATITUD": "54° 50' 37.94\" S", "LONGITUD": "68° 28' 59.77\" W", "ALTITUD": "41", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.483271, -54.843872, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Area de acampe Rio pipo", "description": "descripción: <br>TIPO: AREA DE ACAMPE <br>NOMBRE: AREA ACAMPE RÍO PIPO O CAÑADON DEL TORO<br>ROTULO: Area de acampe Rio pipo<br>LATITUD: 54° 49' 12.84\" S<br>LONGITUD: 68° 28' 9.619\" W<br>ALTITUD: 99<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Area de acampe Rio pipo", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "AREA DE ACAMPE ", "NOMBRE": "AREA ACAMPE RÍO PIPO O CAÑADON DEL TORO", "ROTULO": "Area de acampe Rio pipo", "LATITUD": "54° 49' 12.84\" S", "LONGITUD": "68° 28' 9.619\" W", "ALTITUD": "99", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.469339, -54.820235, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Sanitarios", "description": "descripción: <br>TIPO: SANITARIOS<br>NOMBRE: SANITARIOS<br>ROTULO: Sanitarios<br>LATITUD: 54° 50' 14.71\" S<br>LONGITUD: 68° 33' 43.19\" W<br>ALTITUD: 13<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Sanitarios", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "SANITARIOS", "NOMBRE": "SANITARIOS", "ROTULO": "Sanitarios", "LATITUD": "54° 50' 14.71\" S", "LONGITUD": "68° 33' 43.19\" W", "ALTITUD": "13", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.561997, -54.83742, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Linea regular 7", "description": "descripción: <br>TIPO: PARADA LÍNEA REGULAR<br>NOMBRE: PARADA LÍNEA REGULAR<br>ROTULO: Parada línea regular<br>LATITUD: 54° 50' 5.948\" S<br>LONGITUD: 68° 26' 50.83\" W<br>ALTITUD: 132<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Linea regular 7", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "PARADA LÍNEA REGULAR", "NOMBRE": "PARADA LÍNEA REGULAR", "ROTULO": "Parada línea regular", "LATITUD": "54° 50' 5.948\" S", "LONGITUD": "68° 26' 50.83\" W", "ALTITUD": "132", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.447455, -54.834986, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Gendarmería Nacional", "description": "descripción: <br>TIPO: GENDARMERIA NACIONAL<br>NOMBRE: GENDARMERIA NACIONAL<br>ROTULO: Gendarmería Nacional<br>LATITUD: 54° 50' 39.59\" S<br>LONGITUD: 68° 33' 50.19\" W<br>ALTITUD: 8<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Gendarmería Nacional", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "GENDARMERIA NACIONAL", "NOMBRE": "GENDARMERIA NACIONAL", "ROTULO": "Gendarmería Nacional", "LATITUD": "54° 50' 39.59\" S", "LONGITUD": "68° 33' 50.19\" W", "ALTITUD": "8", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.563944, -54.844333, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Estacionamiento 5", "description": "descripción: <br>TIPO: ESTACIONAMIENTO<br>NOMBRE: ESTACIONAMIENTO<br>ROTULO: Estacionamiento<br>LATITUD: 54° 50' 47.24\" S<br>LONGITUD: 68° 28' 49.52\" W<br>ALTITUD: 17<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Estacionamiento 5", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACIONAMIENTO", "NOMBRE": "ESTACIONAMIENTO", "ROTULO": "Estacionamiento", "LATITUD": "54° 50' 47.24\" S", "LONGITUD": "68° 28' 49.52\" W", "ALTITUD": "17", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.480422, -54.846457, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Isla Redonda", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: ISLA REDONDA<br>ROTULO: Isla Redonda<br>LATITUD: 54° 51' 49.69\" S<br>LONGITUD: 68° 28' 58.41\" W<br>ALTITUD: 42<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Isla Redonda", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "ISLA REDONDA", "ROTULO": "Isla Redonda", "LATITUD": "54° 51' 49.69\" S", "LONGITUD": "68° 28' 58.41\" W", "ALTITUD": "42", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.482893, -54.863804, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Área de Acampe Laguna del Caminante", "description": "descripción: <br>TIPO: AREA DE ACAMPE <br>NOMBRE: AREA ACAMPE LAGUNA VERDE<br>ROTULO: Área de Acampe Laguna del Caminante<br>LATITUD: 54° 45' 31.29\" S<br>LONGITUD: 68° 26' 43.10\" W<br>ALTITUD: 584<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Área de Acampe Laguna del Caminante", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "AREA DE ACAMPE ", "NOMBRE": "AREA ACAMPE LAGUNA VERDE", "ROTULO": "Área de Acampe Laguna del Caminante", "LATITUD": "54° 45' 31.29\" S", "LONGITUD": "68° 26' 43.10\" W", "ALTITUD": "584", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.445306, -54.758694, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "Cerro Guanaco", "description": "descripción: <br>TIPO: TOPONIMIA<br>NOMBRE: CERRO GUANACO<br>ROTULO: Cerro Guanaco<br>LATITUD: 54° 49' 2.510\" S<br>LONGITUD: 68° 30' 37.90\" W<br>ALTITUD: 938<br>AREA_PROTE: Parque Nacional Tierra del Fuego<br>name: Cerro Guanaco", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "TOPONIMIA", "NOMBRE": "CERRO GUANACO", "ROTULO": "Cerro Guanaco", "LATITUD": "54° 49' 2.510\" S", "LONGITUD": "68° 30' 37.90\" W", "ALTITUD": "938", "AREA_PROTE": "Parque Nacional Tierra del Fuego" }, "geometry": { "type": "Point", "coordinates": [ -68.510529, -54.817364, 0.0 ] } },
         { "type": "Feature", "properties": { "Name": "", "description": "descripción: <br>TIPO: ESTACION FERROCARRIL<br>NOMBRE: ESTACION DEL FIN DEL MUNDO<br>ROTULO: Estación del Fin del Mundo<br>LATITUD: 54° 50' 0.122\" S<br>LONGITUD: 68° 25' 25.49\" W<br>ALTITUD: 75<br>AREA_PROTE: <br>name: ", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "descripci__n": "", "TIPO": "ESTACION FERROCARRIL", "NOMBRE": "ESTACION DEL FIN DEL MUNDO", "ROTULO": "Estación del Fin del Mundo", "LATITUD": "54° 50' 0.122\" S", "LONGITUD": "68° 25' 25.49\" W", "ALTITUD": "75", "AREA_PROTE": "" }, "geometry": { "type": "Point", "coordinates": [ -68.423748, -54.833367, 0.0 ] } }
      ]
   }
      
   const getId = (id) => Promise.resolve(jsonPuntoInteres)
   const getList = () => Promise.resolve(jsonPuntoInteresLists)

   return {
      getId,
      getList
   }
}

export default {
create
}