
export default AS = {
    1: require('./weather-icons/1.png'),
    2: require('./weather-icons/2.png'),
    3: require('./weather-icons/3.png'),
    4: require('./weather-icons/4.png'),
    5: require('./weather-icons/5.png'),
    6: require('./weather-icons/6.png'),
    7: require('./weather-icons/7.png'),
    8: require('./weather-icons/8.png'),
    11: require('./weather-icons/11.png'),
    12: require('./weather-icons/12.png'),
    13: require('./weather-icons/13.png'),
    14: require('./weather-icons/14.png'),
    15: require('./weather-icons/15.png'),
    16: require('./weather-icons/16.png'),
    17: require('./weather-icons/17.png'),
    18: require('./weather-icons/18.png'),
    19: require('./weather-icons/19.png'),
    20: require('./weather-icons/20.png'),
    21: require('./weather-icons/21.png'),
    22: require('./weather-icons/22.png'),
    23: require('./weather-icons/23.png'),
    24: require('./weather-icons/24.png'),
    25: require('./weather-icons/25.png'),
    26: require('./weather-icons/26.png'),
    29: require('./weather-icons/29.png'),
    30: require('./weather-icons/30.png'),
    31: require('./weather-icons/31.png'),
    32: require('./weather-icons/32.png'),
    33: require('./weather-icons/33.png'),
    34: require('./weather-icons/34.png'),
    35: require('./weather-icons/35.png'),
    36: require('./weather-icons/36.png'),
    37: require('./weather-icons/37.png'),
    38: require('./weather-icons/38.png'),
    39: require('./weather-icons/39.png'),
    40: require('./weather-icons/40.png'),
    41: require('./weather-icons/41.png'),
    42: require('./weather-icons/42.png'),
    43: require('./weather-icons/43.png'),
    44: require('./weather-icons/44.png'),
  };

